### ISSUE TITLE
Parse output value by float64 is not accurate

### ISSUE THREAD

**Issue by wmh** [btc-script-explorer/scantool#30]
use `decimal` instead

```go
value := floatAmountToUintValue(outputJson["value"].(float64))
```

```go
package btc

import "github.com/shopspring/decimal"

func floatAmountToUintValue(amount float64) uint64 {
	d := decimal.NewFromFloat(amount)
	return uint64(d.Mul(decimal.NewFromInt(100000000)).IntPart())
}
```

**Comment by nonfungible-human** [comment]
This change has been added to [Release v1.0.0](https://github.com/btc-script-explorer/scantool/releases/tag/v1.0.0).

Was there a specific transaction that was reporting an incorrect output value, or was it just something you noticed in the code? The change has been made but I don't have a specific transaction to test it with to verify that it is returning a correct value where it used to return an incorrect value.

**Comment by wmh** [comment]
try testnet tx: `6856e198907e75bf83e2bedc39900fe3d1a54c865aed9c480bc04ef28d395907`
the first output value should be `216751508`

```go
f := 2.16751508
v := uint64(f * 100000000)
fmt.Println(v) // 216751507
```

**Comment by nonfungible-human** [comment]
I tested that value in version 1.0.0 and it reported the correct value. So I am going to close this issue. If you still see the error, or if you notice any other problems, please create a new issue.
